apiVersion: v1 
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.48.4.111
    path: "/"
  persistentVolumeReclaimPolicy: Delete